services:
  backend:
    build:
      context: ./Backend/src
      dockerfile: Dockerfile
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=aws-0-ap-southeast-1.pooler.supabase.com;Database=postgres;Username=postgres.itrqgmrnicfrxllxwryv;Password=ABCP@ssw0rd!;SSL Mode=Require;Trust Server Certificate=true;
    networks:
      - abc-network

  frontend:
    build:
      context: ./Frontend/abc-client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8080
    depends_on:
      - backend
    networks:
      - abc-network

networks:
  abc-network:
    driver: bridge
